name: Build and Push DockerHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build --no-daemon

    - uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_USERNAME }}/ubc-schedule-me-server

    - name: Push to DockerHub
      run: docker push ${{ secrets.REGISTRY_USERNAME }}/ubc-schedule-me-server
